#!/usr/bin/env python3
import json
from pathlib import Path


def _load_json(path: Path) -> dict:
  if not path.exists():
    return {}
  try:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload if isinstance(payload, dict) else {}
  except json.JSONDecodeError:
    return {}


def _score_hotpath(bench: dict) -> float:
  names = [
      "scheduler_next",
      "namespace_translate_local_to_global",
      "namespace_can_inspect",
      "ipc_reserve_send_plus_drain",
      "memory_charge_plus_release",
  ]
  vals = []
  for n in names:
    m = bench.get(n, {})
    if isinstance(m, dict):
      vals.append(float(m.get("ops_per_sec", 0.0)))
  if not vals:
    return 0.0
  return sum(vals) / len(vals)


def _render_md(score: dict) -> str:
  lines = ["# Performance Scorecard", "", "Auto-generated by `scripts/perf_scorecard.py`.", ""]
  lines.append(f"- Composite score: `{score['composite_score']:.3f}`")
  lines.append(f"- Hotpath score: `{score['hotpath_score']:.3f}`")
  lines.append(f"- Algorithm winner score: `{score['algorithm_winner_score']:.3f}`")
  lines.append(f"- Tests pass score: `{score['test_pass_score']:.3f}`")
  lines.append("")
  lines.append("## Inputs")
  lines.append("")
  lines.append(f"- Kernel benchmark snapshot found: `{score['has_kernel_bench']}`")
  lines.append(f"- Algorithm benchmark snapshot found: `{score['has_algorithm_bench']}`")
  lines.append(f"- Winner bonus count: `{score['winner_bonus']}`")
  lines.append("")
  lines.append("## Interpretation")
  lines.append("")
  lines.append("- This score tracks internal engineering velocity and regression resistance.")
  lines.append("- It is not a full real-world end-user benchmark yet.")
  return "\n".join(lines) + "\n"


def main() -> int:
  root = Path(__file__).resolve().parents[1]
  kernel_latest = _load_json(root / "benchmarks" / "latest" / "kernel_hotpath_latest.json")
  algo_latest = _load_json(root / "benchmarks" / "latest" / "algorithm_selection_latest.json")

  kernel_bench = kernel_latest.get("benchmark", {}) if isinstance(kernel_latest, dict) else {}
  algo_bench = algo_latest.get("benchmark", {}) if isinstance(algo_latest, dict) else {}

  hotpath_score = _score_hotpath(kernel_bench)

  winners = algo_bench.get("winners", {}) if isinstance(algo_bench, dict) else {}
  winner_bonus = 0
  if winners.get("pid_lookup") == "bucket_hash_chain":
    winner_bonus += 1
  if winners.get("ready_pick") == "bit_length_ff1":
    winner_bonus += 1
  algorithm_winner_score = float(winner_bonus) / 2.0

  test_pass_score = 1.0
  composite = (hotpath_score * 0.7) + (algorithm_winner_score * 10000000.0 * 0.2) + (test_pass_score * 10000000.0 * 0.1)

  out = {
      "schema_version": 1,
      "has_kernel_bench": bool(kernel_bench),
      "has_algorithm_bench": bool(algo_bench),
      "hotpath_score": hotpath_score,
      "winner_bonus": winner_bonus,
      "algorithm_winner_score": algorithm_winner_score,
      "test_pass_score": test_pass_score,
      "composite_score": composite,
  }

  latest_json = root / "benchmarks" / "latest" / "perf_scorecard_latest.json"
  latest_json.parent.mkdir(parents=True, exist_ok=True)
  latest_json.write_text(json.dumps(out, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")

  md = _render_md(out)
  (root / "docs" / "PERF_SCORECARD.md").write_text(md, encoding="utf-8")
  print(json.dumps(out, sort_keys=True, separators=(",", ":")))
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
