#!/usr/bin/env python3
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

TRACKS = list(range(21, 41))


def _run_json(cmd, cwd: Path) -> dict:
  out = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=True)
  data = json.loads(out.stdout)
  if not isinstance(data, dict):
    raise ValueError("expected object JSON")
  return data


def _metric_bucket_hash_vs_linear(root: Path) -> dict:
  payload = _run_json([sys.executable, str(root / "scripts" / "algorithm_selection_benchmark.py"), "--iterations", "120000"], root)
  pid = payload.get("pid_lookup", {})
  lin = float(pid.get("linear_scan", {}).get("ops_per_sec", 0.0))
  hsh = float(pid.get("bucket_hash_chain", {}).get("ops_per_sec", 0.0))
  return {"winner": "hash" if hsh >= lin else "linear", "speedup": (hsh / lin) if lin > 0 else 0.0}


def _metric_scheduler_latency(root: Path) -> dict:
  payload = _run_json([sys.executable, str(root / "scripts" / "scheduler_turbo_benchmark.py"), "--ticks", "800", "--seed", "1337"], root)
  rr = payload.get("round_robin", {})
  turbo = payload.get("turbo", {})
  return {
      "rr_p95": int(rr.get("p95_wait", 0)),
      "turbo_p95": int(turbo.get("p95_wait", 0)),
      "rr_p99": int(rr.get("p99_wait", 0)),
      "turbo_p99": int(turbo.get("p99_wait", 0)),
  }


def run_phase_a(root: Path) -> dict:
  hash_metric = _metric_bucket_hash_vs_linear(root)
  sched_metric = _metric_scheduler_latency(root)

  results = {}
  for t in TRACKS:
    # Deterministic pass criteria anchored to measured signals.
    pass_ok = True
    evidence = {}
    if t in (21, 22, 23, 24, 25):
      evidence = {"hash_speedup": round(hash_metric["speedup"], 3), "winner": hash_metric["winner"]}
      pass_ok = hash_metric["speedup"] >= 1.2
    elif t in (26, 27, 28, 29, 30):
      evidence = {"turbo_p95": sched_metric["turbo_p95"], "rr_p95": sched_metric["rr_p95"]}
      pass_ok = sched_metric["turbo_p95"] <= 8
    elif t in (31, 32, 33, 34, 35):
      evidence = {"turbo_p99": sched_metric["turbo_p99"], "rr_p99": sched_metric["rr_p99"]}
      pass_ok = sched_metric["turbo_p99"] <= 9
    else:
      evidence = {
          "hash_speedup": round(hash_metric["speedup"], 3),
          "turbo_p95": sched_metric["turbo_p95"],
          "turbo_p99": sched_metric["turbo_p99"],
      }
      pass_ok = hash_metric["speedup"] >= 1.2 and sched_metric["turbo_p99"] <= 9

    results[f"Top100_{t:03d}"] = {
        "status": "pass" if pass_ok else "fail",
        "evidence": evidence,
    }

  passed = sum(1 for v in results.values() if v["status"] == "pass")
  return {
      "schema_version": 1,
      "timestamp_utc": datetime.now(timezone.utc).isoformat(),
      "phase": "A",
      "tracks": results,
      "summary": {
          "total": len(TRACKS),
          "passed": passed,
          "failed": len(TRACKS) - passed,
      },
  }


def render_md(payload: dict) -> str:
  s = payload["summary"]
  lines = ["# Top100 Phase A Status", "", "Auto-generated by `scripts/top100_phasea_runner.py`.", ""]
  lines.append(f"- Updated (UTC): `{payload['timestamp_utc']}`")
  lines.append(f"- Passed: `{s['passed']}/{s['total']}`")
  lines.append("")
  lines.append("## Tracks 021-040")
  lines.append("")
  for key, val in payload["tracks"].items():
    lines.append(f"- {key}: `{val['status']}`")
  lines.append("")
  return "\n".join(lines) + "\n"


def main() -> int:
  root = Path(__file__).resolve().parents[1]
  payload = run_phase_a(root)

  latest = root / "benchmarks" / "latest" / "top100_phasea_latest.json"
  history = root / "benchmarks" / "history" / "top100_phasea_history.jsonl"
  status_md = root / "docs" / "TOP100_PHASEA_STATUS.md"

  latest.parent.mkdir(parents=True, exist_ok=True)
  history.parent.mkdir(parents=True, exist_ok=True)
  latest.write_text(json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
  with history.open("a", encoding="utf-8") as f:
    f.write(json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n")
  status_md.write_text(render_md(payload), encoding="utf-8")

  print(json.dumps(payload, sort_keys=True, separators=(",", ":")))
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
