#!/usr/bin/env python3
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

TRACKS = list(range(41, 61))


def _run_json(cmd, cwd: Path) -> dict:
  out = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=True)
  data = json.loads(out.stdout)
  if not isinstance(data, dict):
    raise ValueError("expected object JSON")
  return data


def _run_gate_ok(cmd, cwd: Path) -> bool:
  rc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
  return rc.returncode == 0


def collect_metrics(root: Path) -> dict:
  algo = _run_json([sys.executable, str(root / "scripts" / "algorithm_selection_benchmark.py"), "--iterations", "150000"], root)
  hotpath = _run_json([sys.executable, str(root / "scripts" / "kernel_hotpath_benchmark.py"), "--iterations", "100000"], root)
  sched = _run_json([sys.executable, str(root / "scripts" / "scheduler_turbo_benchmark.py"), "--ticks", "800", "--seed", "1337"], root)

  pid = algo.get("pid_lookup", {})
  lin = float(pid.get("linear_scan", {}).get("ops_per_sec", 0.0))
  hsh = float(pid.get("bucket_hash_chain", {}).get("ops_per_sec", 0.0))
  hash_speedup = (hsh / lin) if lin > 0 else 0.0

  l_gate = _run_gate_ok([sys.executable, str(root / "scripts" / "scheduler_latency_gate.py"), "--profile", "desktop", "--ticks", "800", "--seed", "1337"], root)
  c_gate = _run_gate_ok([sys.executable, str(root / "scripts" / "code_size_budget_gate.py")], root)
  p_gate = _run_gate_ok([sys.executable, str(root / "scripts" / "perf_scorecard_gate.py"), "--min-samples", "2", "--max-relative-drop", "0.2"], root)

  return {
      "hash_speedup": hash_speedup,
      "scheduler_p95": int(sched.get("turbo", {}).get("p95_wait", 0)),
      "scheduler_p99": int(sched.get("turbo", {}).get("p99_wait", 0)),
      "hotpath_scheduler_ops": float(hotpath.get("scheduler_next", {}).get("ops_per_sec", 0.0)),
      "hotpath_namespace_ops": float(hotpath.get("namespace_translate_local_to_global", {}).get("ops_per_sec", 0.0)),
      "latency_gate_pass": l_gate,
      "codesize_gate_pass": c_gate,
      "scorecard_gate_pass": p_gate,
  }


def evaluate_track(track: int, m: dict) -> dict:
  ok = True
  evidence = {}
  if track in (41, 42, 43, 44, 45):
    evidence = {"scheduler_p95": m["scheduler_p95"], "scheduler_p99": m["scheduler_p99"]}
    ok = m["scheduler_p95"] <= 7 and m["scheduler_p99"] <= 8
  elif track in (46, 47, 48, 49, 50):
    evidence = {"hash_speedup": round(m["hash_speedup"], 3), "namespace_ops": round(m["hotpath_namespace_ops"], 3)}
    ok = m["hash_speedup"] >= 1.2 and m["hotpath_namespace_ops"] > 10000
  elif track in (51, 52, 53, 54, 55):
    evidence = {"codesize_gate_pass": m["codesize_gate_pass"], "scorecard_gate_pass": m["scorecard_gate_pass"]}
    ok = m["codesize_gate_pass"] and m["scorecard_gate_pass"]
  elif track in (56, 57, 58, 59, 60):
    evidence = {
        "latency_gate_pass": m["latency_gate_pass"],
        "codesize_gate_pass": m["codesize_gate_pass"],
        "scorecard_gate_pass": m["scorecard_gate_pass"],
        "scheduler_ops": round(m["hotpath_scheduler_ops"], 3),
    }
    ok = m["latency_gate_pass"] and m["codesize_gate_pass"] and m["scorecard_gate_pass"]
  return {"status": "pass" if ok else "fail", "evidence": evidence}


def run_phase_b(root: Path) -> dict:
  metrics = collect_metrics(root)
  tracks = {f"Top100_{t:03d}": evaluate_track(t, metrics) for t in TRACKS}
  passed = sum(1 for v in tracks.values() if v["status"] == "pass")
  return {
      "schema_version": 1,
      "timestamp_utc": datetime.now(timezone.utc).isoformat(),
      "phase": "B",
      "metrics": metrics,
      "tracks": tracks,
      "summary": {"total": len(TRACKS), "passed": passed, "failed": len(TRACKS) - passed},
  }


def render_md(payload: dict) -> str:
  s = payload["summary"]
  lines = ["# Top100 Phase B Status", "", "Auto-generated by `scripts/top100_phaseb_runner.py`.", ""]
  lines.append(f"- Updated (UTC): `{payload['timestamp_utc']}`")
  lines.append(f"- Passed: `{s['passed']}/{s['total']}`")
  lines.append("")
  lines.append("## Core Metrics")
  lines.append("")
  m = payload["metrics"]
  lines.append(f"- Hash speedup: `{m['hash_speedup']:.3f}x`")
  lines.append(f"- Scheduler p95/p99: `{m['scheduler_p95']}/{m['scheduler_p99']}`")
  lines.append(f"- Gate pass trio (latency/code-size/scorecard): `{m['latency_gate_pass']}/{m['codesize_gate_pass']}/{m['scorecard_gate_pass']}`")
  lines.append("")
  lines.append("## Tracks 041-060")
  lines.append("")
  for key, val in payload["tracks"].items():
    lines.append(f"- {key}: `{val['status']}`")
  lines.append("")
  return "\n".join(lines) + "\n"


def main() -> int:
  root = Path(__file__).resolve().parents[1]
  payload = run_phase_b(root)

  latest = root / "benchmarks" / "latest" / "top100_phaseb_latest.json"
  history = root / "benchmarks" / "history" / "top100_phaseb_history.jsonl"
  status_md = root / "docs" / "TOP100_PHASEB_STATUS.md"

  latest.parent.mkdir(parents=True, exist_ok=True)
  history.parent.mkdir(parents=True, exist_ok=True)
  latest.write_text(json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
  with history.open("a", encoding="utf-8") as f:
    f.write(json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n")
  status_md.write_text(render_md(payload), encoding="utf-8")

  print(json.dumps(payload, sort_keys=True, separators=(",", ":")))
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
